Torrent Suite 3.6 release r59210

diff --git a/dbReports/debian/postinst.in b/dbReports/debian/postinst.in
--- a/dbReports/debian/postinst.in
+++ b/dbReports/debian/postinst.in
@@ -2,10 +2,19 @@
 # Copyright (C) 2010 Ion Torrent Systems, Inc. All Rights Reserved
 set -e
 #set -x
-#echo "preinst $@"
+echo "postinst $@"
 
 case "$1" in
     configure)
+
+    #MegaCli64 library support
+    if [ -e /lib/libsysfs.so.2.0.1 ]; then
+        if [ -h /usr/lib64/libsysfs.so.2.0.2 ]; then
+            echo `ls -l /usr/lib64/libsysfs.so.2.0.2`
+        else
+            ln -s /lib/libsysfs.so.2.0.1 /usr/lib64/libsysfs.so.2.0.2 || true
+        fi
+    fi
 
     chmod ugo+x @ION_INSTALL_PREFIX@/iondb/bin/*
 
@@ -63,7 +72,7 @@ case "$1" in
     # Default Ubuntu file is empty. Config now in /etc/apache2/conf.d/
     touch /etc/apache2/httpd.conf
 
-    #create hard-coded credentials to handle <Location "/basicauthlogout"> within torrent-server.in  
+    #create hard-coded credentials to handle <Location "/basicauthlogout"> within torrent-server.in
     htpasswd -b -c /etc/apache2/users logout logout
 
     # Enable mod_wsgi, mod_rewrite, mod_expires
@@ -127,7 +136,6 @@ case "$1" in
     DAEMONS=(
         ionCrawler
         ionJobServer
-        ionArchive
         ionPlugin
         rabbitmq-server
         celeryd
@@ -142,7 +150,7 @@ case "$1" in
             $CMD
         fi
     done
-    
+
 
     # ------------------------------------------
     # Create directory for logging
@@ -155,7 +163,7 @@ case "$1" in
         chmod a+w /var/log/ion/ionPlugin.log || true
     fi
     # touchy code
-    for log_file in django.log iarchive.log crawl.log ionPlugin.log celery_plugins.log reportsLog.log
+    for log_file in django.log crawl.log ionPlugin.log celery_plugins.log data_management.log
     do
         touch /var/log/ion/$log_file
         chown :www-data /var/log/ion/$log_file
@@ -172,7 +180,7 @@ case "$1" in
     SUDOFILE=/etc/sudoers
     sed -i '/www-data/ d' ${SUDOFILE}
     echo "www-data ALL=(ALL) NOPASSWD: /sbin/shutdown, /usr/bin/at, /usr/bin/aptitude, /usr/bin/apt-get, /usr/sbin/TSconfig, @ION_INSTALL_PREFIX@/onetouch/findHosts.py" >> ${SUDOFILE}
-    
+
     #--------------------------------------------------#
     #---	Remove possible stale ion packages      ---#
     #--------------------------------------------------#
@@ -213,6 +221,8 @@ case "$1" in
         # THIS HAS TO HAPPEN AFTER THE PHP_BASE.HTML FILE IS PUT INTO PLACE DO NOT MOVE
         /usr/bin/python ./bin/install_script.py
 
+        # Loads DMFileSet entries into database
+        /usr/bin/python ./bin/install_dmfilesets.py
 
         # Collect static files (eg. admin pages css/js)
         /usr/bin/python ${DJANGOADMIN} collectstatic --verbosity=0 --noinput --clear --link
@@ -220,23 +230,28 @@ case "$1" in
         cd -
     )
 
-    echo "NODENAME=rabbit@localhost" > /etc/rabbitmq/rabbitmq.conf
-    service rabbitmq-server restart
+    echo "NODENAME=rabbit@localhost" > /etc/rabbitmq/rabbitmq-env.conf
+    cat > /etc/rabbitmq/rabbitmq.config <<EOF
+[
+    {rabbit, [{disk_free_limit, 110000000}]}
+].
+EOF
+    if ! service rabbitmq-server restart; then
+        service rabbitmq-server stop
+        rm -rf /var/lib/rabbitmq/mnesia/rabbit@localhost || true
+        service rabbitmq-server start
+    fi
     invoke-rc.d apache2 restart
-    invoke-rc.d ionCrawler restart
-    invoke-rc.d ionJobServer restart
-    invoke-rc.d ionArchive restart
-    invoke-rc.d ionPlugin restart
     invoke-rc.d celeryd restart
 
     # -------------------------------------------------------------------------
     # Configure Celery's RabbitMQ user, vhost, and permission state
     # -------------------------------------------------------------------------
-    if [[ ! `rabbitmqctl list_users|grep ion` ]]; then
+    if [[ ! `rabbitmqctl list_users|grep ^ion` ]]; then
         echo "Adding RabbitMQ user 'ion'"
         rabbitmqctl add_user ion ionadmin
     fi
-    if [[ ! `rabbitmqctl list_vhosts|grep ion` ]]; then
+    if [[ ! `rabbitmqctl list_vhosts|grep ^ion` ]]; then
         echo "Adding RabbitMQ vhost 'ion' and setting permissions for user 'ion'"
         rabbitmqctl add_vhost ion
         rabbitmqctl set_permissions -p ion ion ".*" ".*" ".*"
@@ -247,51 +262,31 @@ case "$1" in
         echo "Loading references failed."
 
     #load the config page to update plugins and publishers
-    #(wget -q -O /dev/null http://localhost/configure/plugins/ > /dev/null) || \
-    #    echo "Loading plugin config page failed."
-    # Schedule plugin rescan task to run after 30 seconds
-    python -c 'import iondb.bin.djangoinit, iondb.plugins.tasks as tasks; tasks.add_remove_plugins.apply_async(countdown=30)'
+    (wget -q -O /dev/null http://localhost/configure/plugins/ > /dev/null) || \
+        echo "Loading plugin config page failed."
 
-    #TS-5486: Schedule task to rescan all Results/Reports to ensure reportStatus is set to Archived for archived reports
-    python -c 'import iondb.bin.djangoinit, iondb.backup.tasks as tasks; tasks.sync_filesystem_and_db_report_state.apply_async(countdown=30)'
-    
+    # Schedule plugin rescan task to run after various delays, catches plugins installed by other packages.
+    python -c 'import iondb.bin.djangoinit, iondb.plugins.tasks as tasks; tasks.add_remove_plugins.apply_async(countdown=2)'
+    python -c 'import iondb.bin.djangoinit, iondb.plugins.tasks as tasks; tasks.add_remove_plugins.apply_async(countdown=60)'
+
     #TS-5598: Schedule task to fill diskusage field for all Experiments
     python -c 'import iondb.bin.djangoinit, iondb.rundb.tasks as tasks; tasks.backfill_exp_diskusage.apply_async(countdown=40)'
-    #python -c 'import iondb.bin.djangoinit, iondb.rundb.tasks as tasks; tasks.backfill_rep_diskusage.apply_async(countdown=40)'
 
-    # command to execute
-    COMMAND="@ION_INSTALL_PREFIX@/iondb/bin/runnightly.sh"
+    #TS-5908: Schedule task to fix value in Results.diskusage field
+    python -c 'import iondb.bin.djangoinit, iondb.rundb.tasks as tasks; tasks.backfill_result_diskusage.apply_async(countdown=40)'
 
-    # generate two random names for temporary files.
-    FILE="/tmp/$(basename $0).$RANDOM.txt"
-    FILE2="/tmp/$(basename $0).$RANDOM.txt"
+    # Rescan size and inode count for PluginResults
+    python -c 'import iondb.bin.djangoinit, iondb.rundb.tasks as tasks; tasks.backfill_pluginresult_diskusage.apply_async(countdown=40)'
 
-    # Entry we are adding to the crontab.
-    ENTRY="0 6 * * * $COMMAND"
-
-    # read in the users crontab entry into our random file
-    (crontab -u ionadmin -l > $FILE 2> /dev/null) || true
-
-    # Filter out our commands, & put the remaining lines in
-    # our second file
-    (cat $FILE | grep -v "$COMMAND" > $FILE2) || true
-
-    # add our commands to the second file
-    echo "$ENTRY" >> $FILE2
-
-    # reload our file into crontab
-    comm="crontab $FILE2"
-
-    #
-    # use su - username if we are adding to another users crontab.
-    su - ionadmin -c "$comm"
-
-    # remove our tmp files
-    rm $FILE $FILE2
-
+    #TS-6081: Create DMFileStat objs for existing Results objs without them.
+    echo "Migrating to new Data Management..."
+    python -c 'import iondb.bin.djangoinit, iondb.rundb.data.data_management as dm; dm.backfill_create_dmfilestat()'
+    
+    # Now that prerequisite tasks have been run or scheduled, restart crawler.
+    invoke-rc.d ionJobServer restart
+    invoke-rc.d ionPlugin restart
+    invoke-rc.d ionCrawler restart
     ;;
 esac
 
 exit 0
-
-
diff --git a/torrentR/debian/postinst.in b/torrentR/debian/postinst.in
--- a/torrentR/debian/postinst.in
+++ b/torrentR/debian/postinst.in
@@ -1,17 +1,18 @@
 #!/bin/bash
-# Copyright (C) 2010 Ion Torrent Systems, Inc. All Rights Reserved
+# Copyright (C) 2013 Ion Torrent Systems, Inc. All Rights Reserved
 
 set -e
 
 case "$1" in
     configure)
+    #N.B. These are in dependency order: do not sort alphabetically.
     LIBLIST=(\
-            bitops_1.0-4.1.tar.gz \
-            caTools_1.11.tar.gz \
-            gtools_2.6.2.tar.gz \
-            gdata_2.8.1.tar.gz \
-            gplots_2.8.0.tar.gz \
-	    Rcpp_0.7.8.tar.gz \
+        bitops_1.0-4.1.tar.gz \
+        caTools_1.11.tar.gz \
+        gtools_2.6.2.tar.gz \
+        gdata_2.8.1.tar.gz \
+        gplots_2.8.0.tar.gz \
+	    Rcpp_0.10.3.tar.gz \
 	    digest_0.4.2.tar.gz \
 	    spam_0.22-0.tar.gz \
 	    fields_6.3.tar.gz \
@@ -36,8 +37,8 @@ case "$1" in
 	    ellipse_0.3-5.tar.gz \
 	    ROCR_1.0-4.tar.gz \
 	    geneplotter_1.26.0.tar.gz \
-            Hmisc_3.8-3.tar.gz \
-            RCurl_1.6-6.tar.gz \
+        Hmisc_3.8-3.tar.gz \
+        RCurl_1.6-6.tar.gz \
 	    rjson_0.2.9.tar.gz \
 	    rbamtools_2.0.1.tar.gz \
 	    BiocGenerics_0.2.0.tar.gz \
@@ -53,14 +54,14 @@ case "$1" in
 	    getopt_1.17.tar.gz \
 	    optparse_0.9.5.tar.gz \
     )
-    
+
     # force removal of packages
     rm -rf /usr/local/lib/R/site-library/caTools/
     rm -rf /usr/local/lib/R/site-library/proto/
     rm -rf /usr/local/lib/R/site-library/bitops/
     rm -rf /usr/local/lib/R/site-library/fields/
     rm -rf /usr/local/lib/R/site-library/ROCR/
-    
+
     for LIB in ${LIBLIST[@]}; do
         LIBNAME=${LIB%_*}
         LIBVERSION=${LIB#*_}
@@ -82,33 +83,34 @@ case "$1" in
                 echo "No DESCRIPTION file"
             fi
         fi
-        
+
         if [ $NEED_INSTALL -eq 1 ]; then
             echo "Installing $LIB"
             rm -f $LIB # clear any previous downloaded files
-            if ! wget -P /tmp http://updates.iontorrent.com/plugins/$LIB; then
-                
-                # If network connection fails, look for a local supplier of the module file
-                # USB Installer is run with ./updates/Rmodules subdirectory
-                
-                src=${src-$(find /media -type d -name Rmodules | head -1)}    # defines src if it is not defined yet
-                #                                                               ensure there is only one directory defined by $src
-                if [ -z $src ]; then
+
+            src=${src-$(find /media -type d -name Rmodules | head -1)}    # defines src if it is not defined yet
+            #                                                               ensure there is only one directory defined by $src
+            if [ -z $src ]; then
+                #echo "Failed to locate local source for $LIB file"
+                # Try network location
+                if ! wget -P /tmp http://updates.iontorrent.com/plugins/$LIB > /tmp/install_$LIBNAME.log 2>&1; then
+                    #double fail. abort
                     echo "Failed to locate source for $LIB file"
-                    return 1
+                    exit 1
                 fi
-                
+            else
                 cp -v ${src}/$LIB /tmp
             fi
             rm -rf $DIR/$LIBNAME # remove previously-installed library
-            R CMD INSTALL /tmp/$LIB
+            if ! R CMD INSTALL /tmp/$LIB > /tmp/install_$LIBNAME.log 2>&1; then
+                echo "Error during install: see /tmp/install_${LIBNAME}.log"
+                exit 1
+            fi
             rm -f /tmp/$LIB
         fi
     done
-    
+
     ;;
 esac
 
 exit 0
-
-
diff --git a/tsconfig/bin/TSinit b/tsconfig/bin/TSinit
--- a/tsconfig/bin/TSinit
+++ b/tsconfig/bin/TSinit
@@ -13,7 +13,12 @@ function print_help()
 {
     echo
     echo "Usage: TSinit [options]"
-    echo -e "\t--setup-results-partition     Create /results partition"
+    echo -e "\t--proton-config               Create /results and /rawdata partition"
+    echo -e "\t--pgm-config                  Create /results partition"
+    echo -e "\t--dev device_name             Specify device to partition, (default: /dev/sdb)"
+    echo -e "\t--test-results directory      Specify mountpoint instead of /results (for testing only)"
+    echo -e "\t--test-rawdata directory      Specify mountpoint instead of /rawdata (for testing only)"
+    echo -e "\t-d,--debug                    Enable debug print (set -x)"
     echo -e "\t--help, -h                    Prints command line args"
     echo -e "\t--version                     Prints version"
     echo
@@ -32,11 +37,27 @@ function needs_root()
     return 0
 }
 
+function migrate_contents()
+{
+    device=$1
+    mtpoint=$2
+
+    mkdir -p /mnt/tmp_$mtpoint
+    mount $device /mnt/tmp_$mtpoint
+    rsync -av $mtpoint/ /mnt/tmp_$mtpoint
+    umount $device
+    rmdir /mnt/tmp_$mtpoint
+    rm -rf $mtpoint/*
+}
+
 #---                                    ---#
 #--- Variable Declarations              ---#
 #---                                    ---#
 version=`echo '$Revision: 30408 $'|awk '{print $2}'`
 SETUP_RESULTS_PARTITION=0
+SETUP_RAWDATA_PARTITION=0
+results_mtpt="/results"
+rawdata_mtpt="/rawdata"
 
 #---                                    ---#
 #--- Command Line Options Parsing       ---#
@@ -48,11 +69,30 @@ if [ $# == 0 ]; then
     exit 0
 fi
 
+#Default device to partition is
+dev="/dev/sdb"
+
 #---    We convert all arguments to lower case  ---#
 while [ $# != 0 ]; do
     case ${1,,} in
-        '-s'|'--setup-results-partition')
+        '--proton-config')
             SETUP_RESULTS_PARTITION=1
+            SETUP_RAWDATA_PARTITION=1
+        ;;
+        '--pgm-config')
+            SETUP_RESULTS_PARTITION=1
+        ;;
+        '--dev')
+            shift
+            dev=$1
+        ;;
+        '--test-results')
+            shift
+            results_mtpt=$1
+        ;;
+        '--test-rawdata')
+            shift
+            rawdata_mtpt=$1
         ;;
         '-d'|'--debug')
         	set -x
@@ -81,11 +121,11 @@ done
 #---                                    ---#
 #--- Main Execution                     ---#
 #---                                    ---#
-if [ $SETUP_RESULTS_PARTITION -eq 1 ]; then
+if [ $SETUP_RESULTS_PARTITION -eq 1 -a $SETUP_RAWDATA_PARTITION -eq 1 ]; then
 
     # Must have root permissions to continue
     needs_root
-    
+
     #
     # Sets up a new partition on dedicated hardware for Torrent Server
     #
@@ -96,21 +136,23 @@ if [ $SETUP_RESULTS_PARTITION -eq 1 ]; then
     #   - Delete all files in /results on /dev/sda1
     #   - mount /dev/sdb1 at /results
     #   (See jira issue TS-3559 for more details)
-    
-    dev="/dev/sdb"
-    #dev="/dev/sda"
-    
+
     if ! test -b ${dev}; then
         echo "Device: $dev does not exist.  Exiting."
         exit
     fi
-    
+
     # install pre-requisites: parted
     if ! dpkg -l parted|grep -q ^ii; then
         apt-get install parted
     fi
-    
+
     # Get user confirmation
+    echo
+    echo
+    echo "This will create two partitions on ${dev} and format and mount"
+    echo "them at $results_mtpt and $rawdata_mtpt mountpoints."
+    echo "The contents of the current $results_mtpt will migrate to the new partition."
     echo
     echo "WARNING!  Any data on partition ${dev} will be deleted"
     echo "Continue only if you are sure you want to reformat ${dev}"
@@ -118,13 +160,13 @@ if [ $SETUP_RESULTS_PARTITION -eq 1 ]; then
     if [ "$usrin" != "Yes" ]; then
         exit
     fi
-    
-    # Create GPT partition table and one primary partition
+
+    # Create GPT partition table and two primary partitions
     parted ${dev} mklabel gpt
-    parted ${dev} mkpart primary 1 10751488
-    parted ${dev} mkpart primary 10751488 26999808
-    
-        
+    parted ${dev} mkpart primary 0% 40%
+    parted ${dev} mkpart primary 40% 100%
+
+
     # Format the partition with ext4 filesystem
     # Note: will not work for filesystems > 16TB, using Ubuntu 10.04 mkfs package.
     if ! mkfs.ext4 ${dev}1; then
@@ -135,24 +177,97 @@ if [ $SETUP_RESULTS_PARTITION -eq 1 ]; then
         echo "there was an error in mkfs.ext4 formatting ${dev}2"
         exit 1
     fi
-    
+
+    # Prepare raw data directory
+    mkdir -p $rawdata_mtpt
+    chmod 777 $rawdata_mtpt
+    mount ${dev}2 $rawdata_mtpt
+    echo "${dev}2 has been mounted at $rawdata_mtpt"
+
     # Move contents of current /results directory to new partition
-    mkdir -p /rawdata
-    mkdir -p /mnt/tmpresults
-    mount /dev/sdb1 /mnt/tmpresults
-    rsync -av /results/ /mnt/tmpresults
-    umount /dev/sdb1
-    rmdir /mnt/tmpresults
-    rm -rf /results/*
-    mount /dev/sdb1 /results
-    
-    #Edit /etc/fstab to automount at boot
-    if ! grep "^/dev/sdb1" /etc/fstab; then
-        echo -e "/dev/sdb1\t/results\text4\tdefaults\t0 0" >> /etc/fstab
+    if [ -d $results_mtpt ]; then
+        migrate_contents ${dev}1 $results_mtpt
+    else
+        mkdir -p $results_mtpt
+        chmod 777 $results_mtpt
     fi
-    if ! grep "^/dev/sdb2" /etc/fstab; then
-        echo -e "/dev/sdb2\t/rawdata\text4\tdefaults\t0 0" >> /etc/fstab
+
+    mount ${dev}1 $results_mtpt
+    echo "${dev}1 has been mounted at $results_mtpt"
+
+    #Edit /etc/fstab to automount at boot
+    if ! grep "^${dev}1" /etc/fstab; then
+        echo -e "${dev}1\t${results_mtpt}\text4\tdefaults\t0 0" >> /etc/fstab
+    fi
+    if ! grep "^${dev}2" /etc/fstab; then
+        echo -e "${dev}2\t${rawdata_mtpt}\text4\tdefaults\t0 0" >> /etc/fstab
+    fi
+
+elif [ $SETUP_RESULTS_PARTITION -eq 1 -a $SETUP_RAWDATA_PARTITION -eq 0 ]; then
+
+    # Must have root permissions to continue
+    needs_root
+
+    #
+    # Sets up a new partition on dedicated hardware for Torrent Server
+    #
+    #   - check for /dev/sdb1 and exit if it doesn't exist
+    #   - display partition info
+    #   - create GPT partition and format as ext4
+    #   - copy /results on /dev/sda1 to /results on /dev/sdb1
+    #   - Delete all files in /results on /dev/sda1
+    #   - mount /dev/sdb1 at /results
+    #   (See jira issue TS-3559 for more details)
+
+    if ! test -b ${dev}; then
+        echo "Device: $dev does not exist.  Exiting."
+        exit
+    fi
+
+    # install pre-requisites: parted
+    if ! dpkg -l parted|grep -q ^ii; then
+        apt-get install parted
+    fi
+
+    # Get user confirmation
+    echo
+    echo
+    echo "This will create a single partition on ${dev} and format and mount"
+    echo "it at $results_mtpt mountpoint.  The contents of the current $results_mtpt will"
+    echo "migrate to the new partition."
+    echo
+    echo "WARNING!  Any data on partition ${dev} will be deleted"
+    echo "Continue only if you are sure you want to reformat ${dev}"
+    read -p"Type Yes to continue: " usrin
+    if [ "$usrin" != "Yes" ]; then
+        exit
+    fi
+
+    # Create GPT partition table and one primary partition
+    parted ${dev} mklabel gpt
+    parted ${dev} mkpart primary 0% 100%
+
+    # Format the partition with ext4 filesystem
+    # Note: will not work for filesystems > 16TB, using Ubuntu 10.04 mkfs package.
+    if ! mkfs.ext4 ${dev}1; then
+        echo "there was an error in mkfs.ext4 formatting ${dev}1 "
+        exit 1
+    fi
+
+    # Move contents of current /results directory to new partition
+    if [ -d $results_mtpt ]; then
+        migrate_contents ${dev}1 $results_mtpt
+    else
+        mkdir -p $results_mtpt
+        chmod 777 $results_mtpt
+    fi
+    mount ${dev}1 $results_mtpt
+    echo "${dev}1 has been mounted at $results_mtpt"
+
+    #Edit /etc/fstab to automount at boot
+    if ! grep "^${dev}1" /etc/fstab; then
+        echo -e "${dev}1\t$results_mtpt\text4\tdefaults\t0 0" >> /etc/fstab
     fi
 fi
-
+echo -e "\nTSinit is finished\n"
 exit
diff --git a/tsconfig/ts_functions b/tsconfig/ts_functions
--- a/tsconfig/ts_functions
+++ b/tsconfig/ts_functions
@@ -116,12 +116,15 @@ function config_compute_node ()
 function config_ionSoftware()
 {
     # Install/Update system-level software packages
+    updated_mirror_check
     preinst_system_packages
     install_system_packages
     config_system_packages
     # Install/Update Torrent Suite software packages
+    preinst_ion_packages
     install_ion_packages
     config_ion_packages
+    update_conf_file
 }
 
 #-------------------------------------------------
@@ -141,6 +144,7 @@ function reconfig_head_node ()
 
     # ensure tag is correct for master node
     touch /opt/ion/.masternode
+    update_conf_file
 
     #config_ionSoftware
     # Here we intend to do all configuration steps without updating any ion software packages
@@ -173,6 +177,7 @@ function reconfig_compute_node ()
 
     # ensure tag is correct for compute node
     touch /opt/ion/.computenode
+    update_conf_file
 
     # Get name of head node server
     get_user_input_compute
@@ -389,8 +394,10 @@ function ion_daemon_ctrl()
         update-rc.d -f ionCrawler remove
         update-rc.d ionCrawler stop 97 2 3 4 5 .
         # Prevent archiver daemon from starting at boot
-        update-rc.d -f ionArchive remove
-        update-rc.d ionArchive stop 97 2 3 4 5 .
+        if [ -e /etc/init.d/ionArchive  ]; then
+            update-rc.d -f ionArchive remove
+            update-rc.d ionArchive stop 97 2 3 4 5 .
+        fi
         # Prevent plugin daemon from starting at boot
         update-rc.d -f ionPlugin remove
         update-rc.d ionPlugin stop 97 2 3 4 5 .
@@ -783,7 +790,7 @@ function cleanup_previousInstallations()
     # Remove deprecated ion software
     #-----------------------------------
     if dpkg -l|grep -q ion-eaplugins; then
-        apt-get --assume-yes --force-yes remove ion-eaplugins 1>&2 || true
+        dpkg -P ion-eaplugins 1>&2 || true
     fi
 
     #---    Clean up /usr/local/lib/python2.6/dist-packages ---#
@@ -864,7 +871,8 @@ function cleanup_previousInstallations()
     fi
 
     # Remove from the ssh login screen the listing of packages with updates available
-    apt-get --assume-yes --force-yes remove landscape-common 1>&2 || true
+    #apt-get --assume-yes --force-yes remove landscape-common 1>&2 || true
+    dpkg -P landscape-common 1>&2 || true
 
     # Modify dhcp lease time, only if it still the default that our scripts used to set
     if [ -r /etc/dhcp3/dhcpd.conf ]; then
@@ -938,7 +946,7 @@ function pkg_installation ()
         #---                                                                ---#
         #---    Search for Packages.gz file                                 ---#
         #---                                                                ---#
-        updatesPath=$(find $PWD -name Packages.gz 2>/dev/null)
+        updatesPath=$(find $PWD -name Packages.gz | grep updates/Packages.gz 2>/dev/null)
         updatesPath=$(echo $updatesPath|awk '{print $1}')   #filter single entry
         if [ "${updatesPath}" == "" ]; then
             updatesPath=$(find /media -name Packages.gz 2>/dev/null)
@@ -1032,6 +1040,8 @@ function pkg_installation ()
         fi
     done
     echo ""
+
+    cleanup_tmp_src_list $TMP_SRC_LST
 }
 
 
@@ -1060,6 +1070,21 @@ gridengine-exec         shared/gridenginemaster string $(hostname -f)
 gridengine-common       shared/gridenginecell   string iontorrent
 gridengine-common       shared/gridengineconfig boolean true
 EOF
+        # rabbitmq-server install needs preseed
+        debconf-set-selections << EOF
+rabbitmq-server rabbitmq-server/upgrade_previous note
+EOF
+        # rabbitmq-server upgrade to from before 3.0 needs it's conf file removed
+        RMQ_VERSION=`dpkg -l rabbitmq-server|awk '$2 ~ "rabbitmq-server" {print $3}'`
+        #if [[ $RMQ_VERSION < '3.0' ]] && [[ -f /usr/sbin/rabbitmqctl ]]; then
+        if [[ $RMQ_VERSION < '3.0' ]]; then
+            echo Resetting rabbitmq-server, $RMQ_VERSION 1>&2
+            # http://www.rabbitmq.com/clustering.html#upgrading
+            service rabbitmq-server stop 1>&2
+            rm -rf /var/lib/rabbitmq/mnesia/ 1>&2
+        else
+            echo Not resetting rabbitmq-server, $RMQ_VERSION 1>&2
+        fi
     else
         # Preseed the execute gridengine settings
         # sge_master_host is user input on initial config; else its defined in this file
@@ -1088,11 +1113,6 @@ postfix shared/main_mailer_type string  Internet Site
 #postfix shared/recipient_delim string +
 EOF
 
-    # rabbitmq-server install needs preseed
-    debconf-set-selections << EOF
-rabbitmq-server rabbitmq-server/upgrade_previous note
-EOF
-
     # tmpreaper package posts a security notice requiring user acknowledgement
     debconf-set-selections << EOF
 tmpreaper	tmpreaper/readsecurity	note
@@ -1101,8 +1121,22 @@ tmpreaper	tmpreaper/confignowexists	note
 tmpreaper	tmpreaper/readsecurity_upgrading	note
 EOF
 
+    # TS-6230
+    if dpkg -l libapache2-mod-jk|tail -1|grep -q ^ii; then
+        echo "Forcing reinstall of jk.load file" 1>&2
+        apt-get -o Dpkg::Options::="--force-confnew" --reinstall install --assume-yes --force-yes libapache2-mod-jk 1>&2
+    fi
+    if dpkg -l ion-jk|tail -1|grep -q ^ii; then
+        echo "Forcing reinstall of ion-jk" 1>&2
+        apt-get -o Dpkg::Options::="--force-confnew" --reinstall install --assume-yes --force-yes ion-jk 1>&2
+    fi
+
 }
 
+function preinst_ion_packages ()
+{
+    return 0
+}
 
 #Dependency Notes:
 #
@@ -1132,6 +1166,7 @@ function install_system_packages ()
     fi
     return 0
 }
+
 function install_ion_packages()
 {
     user_msg "=================================================================="
@@ -1180,7 +1215,7 @@ function install_ion_packages()
         echo "Critical Error."
         echo "Aborting the configuration now"
         echo
-        dpkg -l "ion-*" tmap samtools
+        dpkg -l "ion-*" samtools
         echo
         exit 1
     fi
@@ -1198,8 +1233,10 @@ function config_ion_packages ()
         if ! service ionJobServer status > /dev/null; then
             /etc/init.d/ionJobServer start || error ${LINENO} "In function install_ion_packages"
         fi
-        if ! service ionArchive status > /dev/null; then
-            /etc/init.d/ionArchive start || error ${LINENO} "In function install_ion_packages"
+        if [ -e /etc/init.d/ionArchive  ]; then
+            if ! service ionArchive status > /dev/null; then
+                /etc/init.d/ionArchive start || error ${LINENO} "In function install_ion_packages"
+            fi
         fi
         if ! service ionPlugin status > /dev/null; then
             /etc/init.d/ionPlugin start || error ${LINENO} "In function install_ion_packages"
@@ -1211,8 +1248,18 @@ function config_ion_packages ()
             service rabbitmq-server start || error ${LINENO} "In function install_ion_packages"
         fi
     fi
+
+    # With 3.6, separate tmap package is no longer distributed; tmap is part of ion-analysis package
+    # In order to not cause confusion, we remove the tmap package
+    if dpkg -l tmap|tail -1|grep -q ^ii; then
+        echo "Removing deprecated package: tmap.  Package ion-analysis now provides tmap." 1>&2
+        #apt-get --assume-yes --force-yes remove tmap 1>&2 || true
+        dpkg -P --ignore-depends=ion-dbreports,ion-alignment tmap 1>&2 || true
+    fi
+
     return 0
 }
+
 function reconfig_ion_packages ()
 {
     echo "=================================================================="
@@ -1756,9 +1803,9 @@ EOFdb
         user_msg "=================================================================="
         user_msg "       Creating backup of postgresql database"
         user_msg "=================================================================="
-        TIMESTAMP=$(date +%Y%m%d_%k%M%S)
-        BACKUP_DBASE_FILE=${BACKUP_DBASE_DIR}/iondb.${TIMESTAMP}.backup
-        /usr/bin/pg_dump -U ion -c iondb | gzip > ${BACKUP_DBASE_FILE}.gz || true
+        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
+        BACKUP_DBASE_FILE="${BACKUP_DBASE_DIR}/iondb.${TIMESTAMP}.backup"
+        /usr/bin/pg_dump -U ion -c iondb | gzip > "${BACKUP_DBASE_FILE}.gz" || true
 
         # Keep 5 most recent dbase backup files
         KEEP=5
@@ -1962,14 +2009,14 @@ function config_master_sge()
         # Assume that only TS serving Proton instruments will have ion-protonupdates installed.
         if is_proton_ts; then
             slots=4
-            qconf -mattr queue slots $slots all.q
+            qconf -mattr queue slots $slots all.q 1>&2
         fi
     fi
 
     # Set the all.q load_thresholds       np_load_avg=95.0
-    qconf -mattr queue load_thresholds np_load_avg=95.0 all.q
-    qconf -mattr queue load_thresholds np_load_avg=95.0 thumbnail.q
-    qconf -mattr queue load_thresholds np_load_avg=95.0 tl.q
+    qconf -mattr queue load_thresholds np_load_avg=95.0 all.q 1>&2
+    qconf -mattr queue load_thresholds np_load_avg=95.0 thumbnail.q 1>&2
+    qconf -mattr queue load_thresholds np_load_avg=95.0 tl.q 1>&2
 
     # add execution host
     #Wait!  host is already an execution host!  This never executes!
@@ -2078,7 +2125,25 @@ function config_master_sge()
     COMPLEX=/tmp/complexresources.$$
     qconf -sc > ${COMPLEX}
     sed -i 's:^mem_free .*:mem_free            mf         MEMORY      <=   YES         YES        0        0:' ${COMPLEX}
+    # Add export_plugins consumable resource
+    if ! grep -q export_plugins ${COMPLEX}; then
+        echo "export_plugins            ep         INT      <=   YES         YES        0        0" >> ${COMPLEX}
+    else
+        sed -i 's:^export_plugins .*:export_plugins            ep         INT      <=   YES         YES        0        0:' ${COMPLEX}
+    fi
     qconf -Mc ${COMPLEX}
+    rm -f "${COMPLEX}"
+    # For network-using plugins, set a consumable resource to control bandwidth utilization
+    NET_CR=10   # Needs experimenting to determine maximum network resource units
+    # ERROR: Was added per-host. Remove and set as global consumable
+    if !qconf -dattr exechost complex_values export_plugins $currentNodeName 1>&2; then
+        user_msg "WARN: unable to clear export_plugins on $currentNodeName. Not set?"
+    fi
+    if ! qconf -aattr exechost complex_values export_plugins=10 global 1>&2; then
+        user_msg "ERROR: unable to set export_plugins consumable resource"
+    fi
+
+    # Restart sge exec daemon
 
     setupQueue=1
     S_RT_LIMIT='24:00:00'       # 24 hours
@@ -2092,6 +2157,11 @@ function config_master_sge()
     #---    Test for existing plugin.q and skip creation if so  ---#
     if qconf -sq plugin.q > /dev/null; then
         setupQueue=0
+        # Ensure current hostname is in plugin queue configuration
+        if ! qconf -aattr queue hostlist $currentNodeName $qname 1>&2; then
+            user_msg "ERROR: SGE config failed setting hostlist"
+            return 1
+        fi
     fi
     if [ $setupQueue -eq 1 ]; then
 
@@ -2169,7 +2239,7 @@ function config_master_sge()
             qconf -aattr queue epilog "/usr/share/ion-tsconfig/gridengine-scripts/plugin-epilog.sh" plugin.q 1>&2
         fi
 
-        qconf -mattr queue load_thresholds np_load_avg=75.0 plugin.q
+        qconf -mattr queue load_thresholds np_load_avg=75.0 plugin.q 1>&2
     fi
 
     # SGE: Set per-host maximum mem_free to be node physical mem
@@ -2182,7 +2252,6 @@ function config_master_sge()
     #    qconf -mattr exechost complex_values mem_free=48G $node # fixed at 48G
     #done
 
-    # Restart sge exec daemon
     #/etc/init.d/gridengine-exec stop
     #/etc/init.d/gridengine-master restart
     /etc/init.d/gridengine-exec start
@@ -2244,6 +2313,11 @@ function config_compute_sge()
     if ! qconf -mattr exechost complex_values mem_free=48G $currentNodeName 1>&2; then
         user_msg "ERROR: error setting mem_free"
         return 1
+    fi
+
+    # ERROR: export set on hosts, should be global. Remove it.
+    if ! qconf -dattr exechost complex_values export_plugins $currentNodeName 1>&2; then
+        user_msg "WARN: unable to clear export_plugins on $currentNodeName. Not set?"
     fi
 
     #add host to queues
@@ -2780,10 +2854,38 @@ function rotate()
     done
 }
 
+function rotate_log_oldversion()
+{
+    MAXINDEX=5
+    # list files in reverse order
+    list=( $TSCONFIG_INSTALL_LOG $TSCONFIG_DEBUG_LOG )
+    for filename in ${list[@]}; do
+        for file in $(ls -r $TSCONFIG_LOG_DIR/$filename* 2>/dev/null); do
+            name=$(basename $file)
+            if [ "$name" == "$filename" ]; then
+                # echo "add an extension";
+                # echo "$file -> $file.1"
+                mv $file $file.1
+                continue
+            fi
 
+            extension=${name##*.}
+
+            if [[ $extension -ge $MAXINDEX ]]; then
+                # echo "remove $file";
+                rm -f $file
+            else
+                # echo "increment index extension by 1"
+                # echo "$file -> ${file%.*}.$(($extension+1))"
+                mv $file ${file%.*}.$(($extension+1))
+            fi
+        done
+    done
+}
+#broken...
 function rotate_log()
 {
-    list=( $TSCONFIG_DIR/$TSCONFIG_INSTALL_LOG $TSCONFIG_DIR/$TSCONFIG_DEBUG_LOG )
+    list=( $TSCONFIG_LOG_DIR/$TSCONFIG_INSTALL_LOG $TSCONFIG_LOG_DIR/$TSCONFIG_DEBUG_LOG )
     for filename in ${list[@]}; do
         rotate $filename
     done
@@ -2871,6 +2973,51 @@ function write_conf_file()
 
     return 0
 }
+
+#---
+#--- This function updates some, not all fields in tsconf.conf
+#---
+function update_conf_file()
+{
+	conflog="$TSCONFIG_DIR/$TSCONFIG_CONF"
+
+    if [ -e $conflog ]; then
+
+    	#--- update the date        ---#
+        sed -i "s/^date:.*/date:`date`/" ${conflog}
+
+        #--- update the hostname    ---#
+        sed -i "s/^hostname:.*/hostname:`hostname -f`/" ${conflog}
+
+        #--- update the ip address  ---#
+        if address=$(dig +short +search `hostname`); then
+            single=`echo $address|awk '{print $1}'`
+            sed -i "s/^ipaddress:.*/ipaddress:$single/" ${conflog}
+        fi
+
+        #--- update the serial number   ---#
+        sn=$(dmidecode -s system-serial-number 2>/dev/null)
+        sn=$(echo $sn|sed 's/\///')    # remove any forward slashes
+        sed -i "s/^serialnumber:.*/serialnumber:$sn/" ${conflog}
+
+        #--- update the hardware name   ---#
+        hardwarename=$(dmidecode -s system-product-name 2>/dev/null | sed 's/^[ \t]*//;s/[ \t]*$//')
+        if ! grep -q ^hardwarename ${conflog}; then
+            echo "hardwarename:\"${hardwarename}\"" >> $conflog
+        else
+            sed -i "s/^hardwarename:.*/hardwarename:\"${hardwarename}\"/"  ${conflog}
+        fi
+
+        #--- update the version ---#
+        version="@ION_VERSION_MAJOR@.@ION_VERSION_MINOR@-@ION_VERSION_RELEASE@"
+        sed -i "s/^version:.*/version:$version/" ${conflog}
+
+    else
+    	echo "Error - could not update $TSCONFIG_CONF"
+        echo "Does not exist: $conflog"
+    fi
+}
+
 
 function copy_conf_file()
 {
@@ -3150,4 +3297,41 @@ function is_proton_ts ()
         echo "This is a Proton TS" 1>&2
         return 0
     fi
+}
+
+# With TS3.6, we have a new web address for Ion package hosting.
+# This function checks/updates /etc/apt/sources.list to include the new address
+# which may offer speed advantage to sites outside US.
+function updated_mirror_check()
+{
+    SRCLIST="/etc/apt/sources.list"
+    APT_ENTRY="deb http://ionupdates.com/updates/software lucid/"
+
+    if [ ! -e $SRCLIST ]; then
+        # major problem if this file doesn't exist
+        echo "Does not exist:${SRCLIST}" 1>&2
+        return 1
+    fi
+
+    if ! grep -q "ionupdates.com" $SRCLIST; then
+
+        echo "The desired apt repository entry does not exist" 1>&2
+
+        if ! grep -q "updates.iontorrent.com" $SRCLIST; then
+
+            echo "The expected apt repository entry does not exist either" 1>&2
+
+            echo $APT_ENTRY >> $SRCLIST
+        else
+
+            echo "Found the expected entry:"
+            # deb http://updates.iontorrent.com/updates/software lucid/
+            # N.B. use of comma as the sed command delimiter.  Insert desired entry
+            # before expected entry
+            sed -i "/updates.iontorrent.com/ s,$,\n${APT_ENTRY}," $SRCLIST
+        fi
+    else
+        echo "An apt repository entry exists with desired web address" 1>&2
+    fi
+
 }
