Torrent Suite Software 5.0.5 Release

diff --git a/tsconfig/bin/TSconfig-ansible b/tsconfig/bin/TSconfig-ansible
--- a/tsconfig/bin/TSconfig-ansible
+++ b/tsconfig/bin/TSconfig-ansible
@@ -75,7 +75,7 @@ if test $EXECUTE; then
         #echo "Valid OS"
         :
     else
-        echo "This release not supported.  Try TSconfig"
+        echo "This release not supported"
         exit 0
     fi
 fi
@@ -178,7 +178,7 @@ done
 # Must be root
 #--------------------------------------
 needs_root
-    
+
 #---                                                                        ---#
 #---    Exit and call script again this time logging all stdout and stderr  ---#
 #---                                                                        ---#
@@ -228,7 +228,7 @@ if [ $CONF_HEAD_NODE == 1 ] || [ $RECONFIGURE == 1 ]; then
     echo "=================================================================="
     echo "Checking available disk space on the root partition"
     echo "=================================================================="
-    free_root=$(df -Pk |grep `mount|grep "on / type"|awk '{print $1}'`|awk '{print $4}')
+    free_root=$(df -k|awk '/.*\/$/ {print $4}')
     log "root partition free space:$free_root kb"
     free_threshold=10485760
         if [[ $free_root -lt $free_threshold ]]; then
@@ -241,12 +241,18 @@ if [ $CONF_HEAD_NODE == 1 ] || [ $RECONFIGURE == 1 ]; then
             user_msg ""
             user_msg "To override this limit, add the '--force' argument"
             user_msg "=================================================================="
-            exit 0
+            exit 1
         else
             log "Warning: Not enough disk space to install software (/ has $free_root kb free)"
             log "User has forced configuration"
         fi
     fi
+
+    # Configure apt repositories
+    config_repositories
+
+    # Install prerequisites
+    install_prerequisites
 
     #============================================================================================
     # Compute Node Handling
@@ -259,7 +265,7 @@ if [ $CONF_HEAD_NODE == 1 ] || [ $RECONFIGURE == 1 ]; then
     fi
 
     if $configure_computes; then
-        
+
         echo "=================================================================="
         echo "Preparing compute nodes for configuration"
         echo "=================================================================="
@@ -279,7 +285,7 @@ if [ $CONF_HEAD_NODE == 1 ] || [ $RECONFIGURE == 1 ]; then
                 ansible computes -i ${ANSIBLE_HOME}/${MY_HOSTS} -m authorized_key -a "user=$TSCONFIG_CLUSTER_ADMIN key='{{ lookup('file', '${ANSIBLE_RSA_KEY}.pub') }}' path=/home/$TSCONFIG_CLUSTER_ADMIN/.ssh/authorized_keys manage_dir=no" --ask-pass -c paramiko 1>&2
             fi
         fi
-        
+
     fi
 
     export ANSIBLE_HOST_KEY_CHECKING=False
@@ -288,7 +294,7 @@ if [ $CONF_HEAD_NODE == 1 ] || [ $RECONFIGURE == 1 ]; then
 
     log "Configure Head Node"
     echo "=================================================================="
-    echo "Starting the site configuration with ansible"
+    echo "Starting the site configuration"
     echo "=================================================================="
     cd $ANSIBLE_HOME
     ansible-playbook site.yml \
@@ -317,36 +323,46 @@ if [ $UPDATE_SOFTWARE == 1 ]; then
 
     log "Torrent Suite update"
     # Root partition space check
-    free_root=$(df -Pk |grep `mount|grep "on / type"|awk '{print $1}'`|awk '{print $4}')
+    free_root=$(df -k|awk '/.*\/$/ {print $4}')
     log "root partition free space:$free_root kb"
     free_threshold=1048576
     if [[ $free_root -lt $free_threshold ]]; then
-
-        log "Not enough disk space to update software (/ has $free_root kb free)"
-        user_msg "=================================================================="
-        user_msg "Not enough disk space to update software"
-        user_msg "/ partition has $free_root kb free and needs $free_threshold kb"
-        user_msg "Ion Software update has been cancelled."
-        user_msg "=================================================================="
-
-    else
-
-        log "Update software"
-        cd $ANSIBLE_HOME
-        ansible-playbook software_update.yml \
-            -i ${ANSIBLE_HOME}/${MY_HOSTS} \
-            --sudo
-
-        if [ $? == 0 ]; then
-            echo "=================================================================="
-            echo "Software Update Complete"
-            echo "=================================================================="
+        if [ $FORCE = False ]; then
+            log "Not enough disk space to update software (/ has $free_root kb free)"
+            user_msg "=================================================================="
+            user_msg "Not enough disk space to update software"
+            user_msg "/ partition has $free_root kb free and needs $free_threshold kb"
+            user_msg "Ion Software update has been cancelled."
+            user_msg ""
+            user_msg "To override this limit, add the '--force' argument"
+            user_msg "=================================================================="
+            exit 1
         else
-            echo "=================================================================="
-            echo "There was an error.  Sorry.  Check the log files."
-            echo "=================================================================="
+            log "Warning: Not enough disk space to install software (/ has $free_root kb free)"
+            log "User has forced configuration"
         fi
+    fi
+    
+    # Configure apt repositories
+    config_repositories
 
+    # Install prerequisites
+    install_prerequisites
+
+    log "Update software"
+    cd $ANSIBLE_HOME
+    ansible-playbook software_update.yml \
+        -i ${ANSIBLE_HOME}/${MY_HOSTS} \
+        --sudo
+
+    if [ $? == 0 ]; then
+        echo "=================================================================="
+        echo "Software Update Complete"
+        echo "=================================================================="
+    else
+        echo "=================================================================="
+        echo "There was an error.  Sorry.  Check the log files."
+        echo "=================================================================="
     fi
 
     exit
@@ -373,11 +389,11 @@ if [ $UPDATE_HOSTNAME == 1 ]; then
 
     # Remove all queues
     for queue in $(qconf -sql); do qconf -dq $queue; done
-    
+
     # Stop gridengine daemons
     service gridengine-exec stop
     service gridengine-master stop
-    
+
     # Set new name (so Ansible will pick it up as {{ansible_hostname}} and {{ansible_fqdn}})
     /bin/hostname ${newHostName}
     echo "${newHostName}" > /etc/hostname
@@ -386,25 +402,25 @@ if [ $UPDATE_HOSTNAME == 1 ]; then
     if [ -f /etc/postfix/main.cf ]; then
         sed -i "s/${oldFQDN}/${newFQDN}/g" /etc/postfix/main.cf
     fi
-    
+
     hostfiles=$(find /usr/share/ion-tsconfig/ansible -name torrentsuite_hosts\*)
     for hostfile in ${hostfiles[@]}; do
         sed -i -e "/^\[headnode\]/ { n ; s/^.*/${newHostName} ansible_connection=local/ }" $hostfile
     done
-    
+
     log "Changing hostname"
     cd $ANSIBLE_HOME
     ansible-playbook rename_headnode.yml \
         -i ${ANSIBLE_HOME}/${MY_HOSTS} \
         --sudo
-    
+
     (
     set +e
     qconf -de $oldFQDN
     qconf -ds $oldFQDN
     qconf -dh $oldFQDN
     )
-    
+
     #DIAGNOSTICS
     if false; then
         echo "===================================================================="
@@ -426,10 +442,13 @@ fi
 if [ $SECURITY_UPDATE == 1 ]; then
     log "Installing security updates"
 
+    #Processes should be stopped, update completed, restart processes
+    ion_daemon_ctrl stop
     cd $ANSIBLE_HOME
     ansible-playbook security_update.yml \
         -i ${ANSIBLE_HOME}/${MY_HOSTS} \
         --sudo
+    ion_daemon_ctrl restart
 fi
 
 #---
diff --git a/tsconfig/ts_functions b/tsconfig/ts_functions
--- a/tsconfig/ts_functions
+++ b/tsconfig/ts_functions
@@ -3714,6 +3714,111 @@ function config_apt_cache() {
 
 }
 
+#-----------------------------------------------------------------------------
+# Perl libraries
+#-----------------------------------------------------------------------------
+function install_perl_libs()
+{
+    # Perl module installation
+    # tarballs are copied to /usr/share/ion-tsconfig/perl
+
+    # To add a Perl module, do 3 steps: add the *.tar.gz file itself
+    # to external/perl directory, add *.tar.gz file name to
+    # tsconfig/debian/postinst.in (this file), and add *.tar.gz file
+    # name to tsconfig/CMakeLists.txt
+
+    staging="/usr/share/ion-tsconfig/perl"
+    cd $staging
+
+    # Find the perl module installation record file.  This file is created once a perl module is installed.
+    # If it is not defined, continue with empty variable.
+    PERLPOD=$(find /usr/local/lib/perl -type f -name perllocal.pod 2>/dev/null)||true
+
+    moduleList=( IO-All-0.44.tar.gz JSON-2.53.tar.gz  JSON-XS-2.32.tar.gz List-MoreUtils-0.33.tar.gz Readonly-1.03.tar.gz Statistics-Descriptive-3.0300.tar.gz Statistics-LineFit-0.07.tar.gz )
+    for module in ${moduleList[@]}; do
+        # Determine if module is not installed yet and install if its not
+        # NOTE: This only checks the perllocal.pod file - it does not verify the modules files exist in the filesystem.
+        # If the files were somehow removed, but the perllocal.pod file not updated, the module would not get installed.
+        module_name=$(echo ${module%-*} |sed s/-/::/)
+        echo "$module_name"
+        if [[ -z $PERLPOD ]]; then
+            # File does not exist, continue with this module installation
+            install_me=true
+        else
+            if ! grep "$module_name" $PERLPOD -A20 | tail -21 | egrep -q '(installed|VERSION)'; then
+                install_me=true
+            else
+                install_me=false
+            fi
+        fi
+
+        if $install_me; then
+            instLog=/tmp/${module%.tar.gz}_install.log
+            echo "Installing ${module%.tar.gz}.  See $instLog"
+            tar zxf $module
+            cd ${module%.tar.gz}
+            perl Makefile.PL > $instLog 2>&1
+            make >> $instLog 2>&1
+            make install >> $instLog 2>&1
+            cd $staging
+            rm -rf ${module%.tar.gz}
+        fi
+    done
+    ldconfig
+}
+
+function install_prerequisites()
+{
+    # Install ansible and customize ansible configuration
+    apt-get install -y --allow-unauthenticated ansible
+
+    # Add hostname to ansible hosts definition file
+    sed -i "s/LOCALHEADNODE.*/$HOSTNAME ansible_connection=local/g" /usr/share/ion-tsconfig/ansible/torrentsuite_hosts
+
+    # Enable Ansible logging
+    sed -i "s:.*log_path.*:log_path = /var/log/ion/tsconfig_debug.log:" /etc/ansible/ansible.cfg
+
+    # Disable strict host key checking
+    sed -i "s:.*host_key_checking.*:host_key_checking = False:" /etc/ansible/ansible.cfg
+
+    # Set the default remote user
+    sed -i "s:.*remote_user.*:remote_user = ionadmin:" /etc/ansible/ansible.cfg
+
+    # Set the private key file
+    sed -i "s:.*private_key_file.*:private_key_file = /home/ionadmin/.ssh/ansible_rsa_key:" /etc/ansible/ansible.cfg
+
+    # Set the default host file
+    sed -i "s:.*hostfile.*:hostfile = /usr/share/ion-tsconfig/ansible/torrentsuite_hosts:" /etc/ansible/ansible.cfg
+
+    # Set the default roles path
+    sed -i "s:.*roles_path.*:roles_path = /usr/share/ion-tsconfig/ansible/roles:" /etc/ansible/ansible.cfg
+
+    # Enable pipelining to speed up ssh
+    sed -i "s:#pipelining.*:pipelining = True:" /etc/ansible/ansible.cfg
+    sed -i "s:^pipelining.*:pipelining = True:" /etc/ansible/ansible.cfg
+
+    # Edit {{ansible_managed}} variable.  We don't want the date stamp
+    sed -i "s/^ansible_managed.*/ansible_managed = Ansible managed: {file}/" /etc/ansible/ansible.cfg
+
+    # Edit contents of all_local
+    if ! /usr/share/ion-tsconfig/ansible/files/update_all_local.sh; then
+        echo "Error during execution of update_all_local.sh"
+        echo "Check contents of all_local against all for any changes"
+    fi
+}
+
+function config_repositories()
+{
+    # lucid is out of support and needs to ensure the ubuntu URL points to old-releases
+    if [[ $(lsb_release -sc) = "lucid" ]]; then
+        # We should never get here on lucid.
+        :
+    else
+        # No-op currently: placeholder until we need it
+        echo "Nothing to be done for $(lsb_release -sc) URLs at this time"
+    fi
+}
+
 function outbound_net_port()
 {
     port=$(/sbin/route | awk '/default/{print $8}')
