Torrent Suite 3.6.2 release r63672

diff --git a/tsconfig/bin/TSconfig b/tsconfig/bin/TSconfig
--- a/tsconfig/bin/TSconfig
+++ b/tsconfig/bin/TSconfig
@@ -14,6 +14,7 @@ set -e
 TSCONFIG_SRC_DIR='/usr/share/ion-tsconfig'
 source $TSCONFIG_SRC_DIR/ts_params
 source $TSCONFIG_SRC_DIR/ts_functions
+LOCK_FILE=/var/lock/tsconfiglock
 
 #--------------------------------------
 # trap exit codes
@@ -27,8 +28,8 @@ EXECUTE=0
 OPTARGS="$@"
 CONF_HEAD_NODE=0        # Enables SGE qmaster,postgres,apache2,/results sharing
 CONF_COMPUTE_NODE=0     # Enables SGE exec
-CONF_PGM_SUPPORT=0      # Enables direct-connected PGMs and data dir sharing
-REMOVE_PGM_SUPPORT=0    # Removes PGM support
+CONF_PGM_SUPPORT=0      # Enables direct-connected instruments and data dir sharing
+REMOVE_PGM_SUPPORT=0    # Removes support for direct-connected instruments
 UPDATE_SOFTWARE=0       # Get software updates and install
 UPDATE_HOSTNAME=0       # Change the hostname (requires reboot)
 CONF_TIME_ZONE=0        # Run timezone configuration script
@@ -40,7 +41,7 @@ INITIAL_CONFIG=1        # Flags interactive configuration settings - only for in
 CHANGE_PASSWORD=0       # Change ionadmin password.
 PURGE_ALL_DEB=0         # Delete all deb package files in apt cache
 RECONFIGURE=0           # Re-run configuration steps only
-version=`echo '$Revision: 43018 $'|awk '{print $2}'`
+version=`echo '$Revision: 62409 $'|awk '{print $2}'`
 
 #---                                    ---#
 #---    Command Line Options Parsing    ---#
@@ -95,11 +96,11 @@ while [ $# != 0 ]; do
             CONF_PGM_SUPPORT=0
         ;;
         '--configure-pgm-support')
-            if [ $EXECUTE == 1 ];then user_msg "Configure PGM support"; fi
+            if [ $EXECUTE == 1 ];then user_msg "Configure direct-connected instrument support"; fi
             CONF_PGM_SUPPORT=1
         ;;
         '--remove-pgm-support')
-            if [ $EXECUTE == 1 ];then user_msg "Remove PGM support"; fi
+            if [ $EXECUTE == 1 ];then user_msg "Remove direct-connected instrument support"; fi
             REMOVE_PGM_SUPPORT=1
             CONF_PGM_SUPPORT=0
         ;;
@@ -129,7 +130,7 @@ while [ $# != 0 ]; do
 		'--eth-dev'|'-e')
 		    shift
 			ETH_DEV=$1
-		    if [ $EXECUTE == 1 ];then user_msg "Ethernet device specified: $ETH_DEV"; fi 
+		    if [ $EXECUTE == 1 ];then user_msg "Ethernet device specified: $ETH_DEV"; fi
 		;;
 		'--apt-usb')
 		    if [ $EXECUTE == 1 ];then user_msg "Use Ion Install USB Drive as apt repository"; fi
@@ -184,6 +185,18 @@ fi
 #---                    ---#
 #---    Main Execution  ---#
 #---                    ---#
+#-----------------------------------------
+# Need to acquire the lock file to proceed
+#-----------------------------------------
+if mkdir $LOCK_FILE; then
+  trap 'rm -rf "$LOCK_FILE"; exit $?' 0
+  PID_LOCKED=1
+  echo "Locking succeeded"
+else
+  echo "Lock failed - is previous instance of TSconfig running?"
+  exit 1
+fi
+
 if [ -f /opt/ion/bin/ion-tsconfig.version.env ]; then
     source /opt/ion/bin/ion-tsconfig.version.env
 fi
@@ -202,14 +215,14 @@ if [ $CONF_PGM_SUPPORT == 1 -a $REMOVE_PGM_SUPPORT == 1 ]; then
     exit 1
 fi
 
-#---    Typical TS config should be with direct connect PGMs enabled    ---#
+#---    Typical TS config should be with direct connect instruments enabled    ---#
 if [ $CONF_HEAD_NODE == 1 ]; then
     if [ $CONF_PGM_SUPPORT == 0 ]; then
-        echo "This server will NOT be configured to support direct-connected PGMs"
+        echo "This server will NOT be configured to support direct-connected instrumentss"
         echo "If this is correct, enter Y and press the Enter key to continue."
         echo "Else, press CTRL-C to exit the script."
         echo "Use TSconfig --help for options."
-        echo -n "Continue?"
+        echo -n "Continue? "
         read -p "Continue? " usrmsg
         case $usrmsg in
         	y|Y)
@@ -224,15 +237,15 @@ fi
 
 #---
 #---    N.B. When a server configuration is specified, all other options are ignored
-#---    except for the CONF_PGM_SUPPORT option 
+#---    except for the CONF_PGM_SUPPORT option
 #---
 if [ $CONF_HEAD_NODE == 1 -o $CONF_COMPUTE_NODE == 1 ]; then
-    
+
     #if ! network_tests $ETH_DEV; then
     #    log "Cannot configure node: Failed network test"
     #    exit 1
     #fi
-    
+
     if [ $CONF_HEAD_NODE == 1 ]; then
     	log "Configure Head Node"
         config_head_node
@@ -240,15 +253,15 @@ if [ $CONF_HEAD_NODE == 1 -o $CONF_COMPUTE_NODE == 1 ]; then
     	log "Configure Compute Node"
         config_compute_node
     fi
-    
-    #Setup PGM support; export raw data directory
+
+    #Setup direct-connected instrument support; export raw data directory
     if [ $CONF_PGM_SUPPORT == 1 ]; then
         config_pgm_support
     elif [ $REMOVE_PGM_SUPPORT == 1 ];then
-    	log "Unconfigure PGM support"
+    	log "Unconfigure direct-connected instrument support"
     	remove_pgm_support
     fi
-    
+
     #Call initial configuration steps which require user input
     if [ $INITIAL_CONFIG == 1 ]; then
         exec 2>&3   # Redirect stderr (which points to a file) back to stderr (console)
@@ -266,7 +279,7 @@ fi
 #---
 if [ $UNCONF_SERVER -eq 1 ]; then
     log "Unconfigure Server"
-	
+
 	echo
 	echo "This will disable the server from functioning as a normal Torrent Server."
 	echo "Only continue if you are prepared to reconfigure the server again."
@@ -276,9 +289,9 @@ if [ $UNCONF_SERVER -eq 1 ]; then
 		log "User-aborted unconfigure operation"
 		exit 0
     fi
-	
+
 	unconfigure_torrentserver
-    
+
     echo "=================================================================="
     echo "Unconfigure server process completed successfully"
     echo "=================================================================="
@@ -298,14 +311,17 @@ if [ $UPDATE_SOFTWARE == 1 ]; then
 		fi
 	fi
 	log "Torrent Suite update"
+    echo "=================================================================="
+    echo "Waiting for Torrent daemons to shutdown"
+    echo "=================================================================="
     ion_daemon_ctrl stop
     config_ionSoftware
-    
+
     echo "=================================================================="
     echo "TSconfig software update process completed successfully"
     echo "=================================================================="
     log "TSconfig process completed successfully"
-    
+
     exit 0
 fi
 
@@ -362,7 +378,7 @@ fi
 #---    N.B. When a delete raw data is specified, all other options are ignored
 #---
 if [ $REMOVE_PGM_SUPPORT == 1 ]; then
-	log "Remove settings supporting direct-connected PGMs"
+	log "Remove settings supporting direct-connected instruments"
     remove_pgm_support
     exit 0
 fi
@@ -387,7 +403,7 @@ fi
 #---
 if [ $PURGE_ALL_DEB == 1 ]; then
     log "Deleting all deb package files"
-    apt-get clean 
+    apt-get clean
 fi
 #---
 #---    This is last because the flag is enabled by default in the script
