Torrent Suite 3.2.1 release r46115

diff --git a/torrentR/debian/postinst.in b/torrentR/debian/postinst.in
--- a/torrentR/debian/postinst.in
+++ b/torrentR/debian/postinst.in
@@ -6,30 +6,57 @@ set -e
 case "$1" in
     configure)
     LIBLIST=(\
+            bitops_1.0-4.1.tar.gz \
+            caTools_1.11.tar.gz \
+            gtools_2.6.2.tar.gz \
+            gdata_2.8.1.tar.gz \
+            gplots_2.8.0.tar.gz \
 	    Rcpp_0.7.8.tar.gz \
 	    digest_0.4.2.tar.gz \
 	    spam_0.22-0.tar.gz \
 	    fields_6.3.tar.gz \
-	    plyr_1.0.3.tar.gz \
-	    reshape_0.8.3.tar.gz \
+	    plyr_1.7.1.tar.gz \
+	    RColorBrewer_1.0-5.tar.gz \
+	    colorspace_1.1-1.tar.gz \
+	    dichromat_1.2-4.tar.gz \
+	    labeling_0.1.tar.gz \
+	    munsell_0.3.tar.gz \
+	    stringr_0.6.tar.gz \
+	    reshape2_1.2.1.tar.gz \
+	    scales_0.2.1.tar.gz \
+	    memoise_0.1.tar.gz \
 	    proto_0.3-8.tar.gz \
-	    ggplot2_0.8.8.tar.gz \
+	    ggplot2_0.9.1.tar.gz \
 	    Biobase_2.8.0.tar.gz \
 	    DBI_0.2-5.tar.gz \
-	    RSQLite_0.9-2.tar.gz \
+	    RSQLite_0.11.1.tar.gz \
 	    AnnotationDbi_1.10.2.tar.gz \
 	    xtable_1.5-6.tar.gz \
 	    annotate_1.26.1.tar.gz \
 	    ellipse_0.3-5.tar.gz \
 	    ROCR_1.0-4.tar.gz \
 	    geneplotter_1.26.0.tar.gz \
-        Hmisc_3.8-3.tar.gz \
-        RCurl_1.6-6.tar.gz \
-        rjson_0.2.5.tar.gz \
+            Hmisc_3.8-3.tar.gz \
+            RCurl_1.6-6.tar.gz \
+	    rjson_0.2.9.tar.gz \
+	    rbamtools_2.0.1.tar.gz \
+	    BiocGenerics_0.2.0.tar.gz \
+	    IRanges_1.14.4.tar.gz \
+	    Biostrings_2.24.1.tar.gz \
+	    GenomicRanges_1.8.9.tar.gz \
+	    zlibbioc_1.2.0.tar.gz \
+	    Rsamtools_1.8.5.tar.gz \
+	    latticeExtra_0.6-19.tar.gz \
+	    hwriter_1.3.tar.gz \
+	    ShortRead_1.14.4.tar.gz \
     )
     
-    # Do the file writing/unpacking in writeable directory
-    cd /tmp
+    # force removal of packages
+    rm -rf /usr/local/lib/R/site-library/caTools/
+    rm -rf /usr/local/lib/R/site-library/proto/
+    rm -rf /usr/local/lib/R/site-library/bitops/
+    rm -rf /usr/local/lib/R/site-library/fields/
+    rm -rf /usr/local/lib/R/site-library/ROCR/
     
     for LIB in ${LIBLIST[@]}; do
         LIBNAME=${LIB%_*}
@@ -56,8 +83,22 @@ case "$1" in
         if [ $NEED_INSTALL -eq 1 ]; then
             echo "Installing $LIB"
             rm -f $LIB # clear any previous downloaded files
-            wget http://updates.iontorrent.com/plugins/$LIB;
-            R CMD INSTALL -l $DIR $LIB
+            if ! wget -P /tmp http://updates.iontorrent.com/plugins/$LIB; then
+                
+                # If network connection fails, look for a local supplier of the module file
+                # USB Installer is run with ./updates/Rmodules subdirectory
+                
+                src=${src-$(find /media -type d -name Rmodules | head -1)}    # defines src if it is not defined yet
+                #                                                               ensure there is only one directory defined by $src
+                if [ -z $src ]; then
+                    echo "Failed to locate source for $LIB file"
+                    return 1
+                fi
+                
+                cp -v ${src}/$LIB /tmp
+            fi
+            rm -rf $DIR/$LIBNAME # remove previously-installed library
+            R CMD INSTALL /tmp/$LIB
             rm -f $LIB
         fi
     done
