Torrent Suite Software 5.12.0 Release

diff --git a/gpu/debian/postinst b/gpu/debian/postinst
--- a/gpu/debian/postinst
+++ b/gpu/debian/postinst
@@ -1,14 +1,9 @@
 #!/bin/bash
 # Copyright (C) 2011 Ion Torrent Systems, Inc. All Rights Reserved
 set -e
-#set -x
-#echo "postinst $@"
+
 case "$1" in
 	configure)
-    
-        # Create ldconfig file
-        echo "/usr/local/cuda/lib64" > /etc/ld.so.conf.d/cuda.conf
-        ldconfig
     
     	# Test for X server running
         if ps -ef|grep /usr/bin/X|grep -v grep >/dev/null; then
@@ -58,32 +53,61 @@ case "$1" in
         
         # Extract Device Driver Package
         echo "Extract Device Driver Package"
-        rm -rf @ION_INSTALL_PREFIX@/devdriver
-        bash @ION_INSTALL_PREFIX@/devdriver_*.run \
+        rm -rf @ION_GPU_PREFIX@/devdriver
+        bash @ION_GPU_PREFIX@/devdriver_*.run \
             --extract-only \
-            --target @ION_INSTALL_PREFIX@/devdriver > /tmp/nvidiadriver_install.log
+            --target @ION_GPU_PREFIX@/devdriver > /tmp/nvidiadriver_install.log
         
         # Prevent nouveau driver from running
         (modprobe -r nouveau) || true
         echo -e "# generated by nvidia-installer\nblacklist nouveau\noptions nouveau modeset=0" > /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
         
         # Run Device Driver installer
+        # catch error in installation before exiting
+        set +e
         echo "Install Nvidia Device Driver (see /tmp/nvidiadriver_install.log)"
-        cd @ION_INSTALL_PREFIX@/devdriver >/dev/null
+        cd @ION_GPU_PREFIX@/devdriver >/dev/null
         ./nvidia-installer \
             --accept-license \
             --no-questions \
             --ui=none \
             --dkms \
-            --run-nvidia-xconfig >> /tmp/nvidiadriver_install.log
+            --run-nvidia-xconfig >& /tmp/nvidiadriver_install.log
+
+        install_status=$?
+        nvidia_installer_log="/var/log/nvidia-installer.log"
+        if [ $install_status -eq 0 ]; then
+          set -e
+        elif [ -e $nvidia_installer_log ]; then
+          if grep -E "NVIDIA Linux graphics driver will ignore this GPU" $nvidia_installer_log >> /dev/null; then
+            echo
+            echo "************************************************"
+            echo
+            echo "WARNING:"
+            echo "Following NVIDIA GPU's are no longer supported on this operating system."
+            echo "Device is:"
+            echo `lspci|grep -i "nvidia"|egrep '(3D controller|VGA compatible controller)'`
+            echo
+        	echo "************************************************"
+            echo
+          else
+            echo "Nvidia driver installation failed. Look for more details in /var/log/nvidia-installer.log"
+          fi  
+          exit $?
+        fi
+       
         cd - >/dev/null
 
         # create nvidia device files
-        @ION_INSTALL_PREFIX@/create_nvidia_files
+        if [ -e /etc/rc.local ]; then 
+            @ION_GPU_PREFIX@/create_nvidia_files
+	fi
         
         # Edit the rc.local file
-        sed -i "/create_nvidia_files/d" /etc/rc.local
-        sed -i "s:^exit 0:@ION_INSTALL_PREFIX@/create_nvidia_files\nexit 0:" /etc/rc.local
+        if [ -e /etc/rc.local ]; then 
+	        sed -i "/create_nvidia_files/d" /etc/rc.local
+                sed -i "s:^exit 0:@ION_GPU_PREFIX@/create_nvidia_files\nexit 0:" /etc/rc.local
+	fi
     	if [ -f "/software/datacollect.avx" ]; then
 		# remove xorg.conf (installed by CUDA)
 		rm -rf /etc/X11/xorg.conf
@@ -97,11 +121,11 @@ case "$1" in
 	;;
     
     abort-install|abort-upgrade)
-    	rm -rf @ION_INSTALL_PREFIX@/devdriver
+    	rm -rf @ION_GPU_PREFIX@/devdriver
         rm -rf /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
-        sed -i "/create_nvidia_files/d" /etc/rc.local
-        rm -f /etc/ld.so.conf.d/cuda.conf
-        ldconfig
+        if [ -e /etc/rc.local ]; then 
+            sed -i "/create_nvidia_files/d" /etc/rc.local
+	    fi
     ;;
 esac
 
